apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: back
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: back
    spec:
      containers:
      - image: bradawk/back
        imagePullPolicy: IfNotPresent
        name: back
        ports:
            - name: http
              containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
