version: '3'

services:
  
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'

  back:
    build: back
    image: bradawk/back
    ports:
      - '80:80'
    links:
      - mongo-db

  # front:
  #   build: front
  #   image: bradawk/front
  #   ports:
  #     - '80:80'
  #   # environment:
  #   #   -API_URL=